// Every output format the tool can put on the clipboard or into a file.
//
// One rule throughout: what you copy is what you paste. No trailing prose, no
// "generated by" banner in the CSS, nothing that has to be deleted before the
// snippet compiles.

export function rgbString({ r, g, b }) {
  return `rgb(${r}, ${g}, ${b})`;
}

export function hslString({ h, s, l }) {
  return `hsl(${Math.round(h)}, ${Math.round(s)}%, ${Math.round(l)}%)`;
}

export function tailwindClass(swatch) {
  return `bg-${swatch.slug}`;
}

function header(palette, source) {
  const where = source && source.name ? ` from ${source.name}` : '';
  return `${palette.name}${where}`;
}

export function toPlainText(palette, source) {
  const lines = [`${header(palette, source)}`, ''];
  for (const c of palette.colors) {
    lines.push(`${c.hex}  ${c.name}${c.role ? ` (${c.role})` : ''}`);
  }
  return lines.join('\n') + '\n';
}

export function toHexList(palette) {
  return palette.colors.map((c) => c.hex).join('\n') + '\n';
}

export function toCss(palette, source) {
  const lines = [`/* ${header(palette, source)} */`, ':root {'];
  for (const c of palette.colors) {
    lines.push(`  --${c.slug}: ${c.hex.toLowerCase()};`);
  }
  lines.push('');
  // The bare channel triplet is what lets a consumer do
  // `rgb(var(--x-rgb) / 40%)` without redeclaring the colour.
  for (const c of palette.colors) {
    lines.push(`  --${c.slug}-rgb: ${c.rgb.r} ${c.rgb.g} ${c.rgb.b};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

// Tailwind v3: a config fragment to merge into tailwind.config.js.
export function toTailwindV3(palette) {
  const lines = [
    '// tailwind.config.js',
    'module.exports = {',
    '  theme: {',
    '    extend: {',
    '      colors: {',
  ];
  for (const c of palette.colors) {
    lines.push(`        '${c.slug}': '${c.hex.toLowerCase()}',`);
  }
  lines.push('      },', '    },', '  },', '};');
  return lines.join('\n') + '\n';
}

// Tailwind v4: colours are CSS custom properties in an @theme block, and the
// utility classes (bg-*, text-*, border-*) are generated from the variable name.
export function toTailwindV4(palette) {
  const lines = ['@theme {'];
  for (const c of palette.colors) {
    lines.push(`  --color-${c.slug}: ${c.hex.toLowerCase()};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

export function toJson(palette, source) {
  return JSON.stringify({
    name: palette.name,
    generator: 'palette.lab980.com',
    extractedAt: new Date().toISOString(),
    source: source
      ? { name: source.name, width: source.width, height: source.height, type: source.type }
      : null,
    sampledPixels: palette.sampled,
    extractionMs: palette.ms,
    colors: palette.colors.map((c) => ({
      name: c.name,
      slug: c.slug,
      role: c.role,
      hex: c.hex,
      rgb: { r: c.rgb.r, g: c.rgb.g, b: c.rgb.b },
      hsl: {
        h: Math.round(c.hsl.h),
        s: Math.round(c.hsl.s),
        l: Math.round(c.hsl.l),
      },
      share: Number(c.ratio.toFixed(4)),
    })),
  }, null, 2) + '\n';
}

export const FORMATS = {
  hex: { label: 'Hex list', ext: 'txt', mime: 'text/plain', build: (p) => toHexList(p) },
  text: { label: 'Text', ext: 'txt', mime: 'text/plain', build: toPlainText },
  css: { label: 'CSS variables', ext: 'css', mime: 'text/css', build: toCss },
  'tailwind-v3': { label: 'Tailwind v3 config', ext: 'js', mime: 'text/javascript', build: (p) => toTailwindV3(p) },
  'tailwind-v4': { label: 'Tailwind v4 @theme', ext: 'css', mime: 'text/css', build: (p) => toTailwindV4(p) },
  json: { label: 'JSON', ext: 'json', mime: 'application/json', build: toJson },
};

export function filenameFor(palette, ext) {
  const base = palette.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `${base || 'palette'}.${ext}`;
}
