// Every output format the tool can put on the clipboard or into a file.
//
// One rule throughout: what you copy is what you paste. No trailing prose, no
// "generated by" banner in the CSS, nothing that has to be deleted before the
// snippet compiles.

import { CVD_TYPES } from './color.js';
import {
  againstExtremes, pairMatrix, buildCards, resolveCard, withBoosts, confusions,
  alternatives, grade, ratioText, truncate,
} from './a11y.js';

export function rgbString({ r, g, b }) {
  return `rgb(${r}, ${g}, ${b})`;
}

export function hslString({ h, s, l }) {
  return `hsl(${Math.round(h)}, ${Math.round(s)}%, ${Math.round(l)}%)`;
}

export function tailwindClass(swatch) {
  return `bg-${swatch.slug}`;
}

function header(palette, source) {
  const where = source && source.name ? ` from ${source.name}` : '';
  return `${palette.name}${where}`;
}

export function toPlainText(palette, source) {
  const lines = [`${header(palette, source)}`, ''];
  for (const c of palette.colors) {
    lines.push(`${c.hex}  ${c.name}${c.role ? ` (${c.role})` : ''}`);
  }
  return lines.join('\n') + '\n';
}

export function toHexList(palette) {
  return palette.colors.map((c) => c.hex).join('\n') + '\n';
}

export function toCss(palette, source) {
  const lines = [`/* ${header(palette, source)} */`, ':root {'];
  for (const c of palette.colors) {
    lines.push(`  --${c.slug}: ${c.hex.toLowerCase()};`);
  }
  lines.push('');
  // The bare channel triplet is what lets a consumer do
  // `rgb(var(--x-rgb) / 40%)` without redeclaring the colour.
  for (const c of palette.colors) {
    lines.push(`  --${c.slug}-rgb: ${c.rgb.r} ${c.rgb.g} ${c.rgb.b};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

// Tailwind v3: a config fragment to merge into tailwind.config.js.
export function toTailwindV3(palette) {
  const lines = [
    '// tailwind.config.js',
    'module.exports = {',
    '  theme: {',
    '    extend: {',
    '      colors: {',
  ];
  for (const c of palette.colors) {
    lines.push(`        '${c.slug}': '${c.hex.toLowerCase()}',`);
  }
  lines.push('      },', '    },', '  },', '};');
  return lines.join('\n') + '\n';
}

// Tailwind v4: colours are CSS custom properties in an @theme block, and the
// utility classes (bg-*, text-*, border-*) are generated from the variable name.
export function toTailwindV4(palette) {
  const lines = ['@theme {'];
  for (const c of palette.colors) {
    lines.push(`  --color-${c.slug}: ${c.hex.toLowerCase()};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

// The accessibility read-out: the same analysis the cards show on screen, as
// something you can paste into a ticket. The matrix lives here rather than on
// the page because a grid of n^2 ratios is a reference, not a decision.
export function toAccessibility(palette, source) {
  const colors = palette.colors;
  // The pairings, the alternatives and the colour-vision findings are
  // properties of the palette rather than of the order it happens to be shown
  // in, so they are computed over the extraction order — which is what the
  // page's own cards use, and what any boost the reader has switched on is
  // keyed to. The listings follow the reader's chosen order, because a listing
  // is a listing.
  const analysed = palette.analysed || colors;
  // Concrete colours by card and slot, not the check indices they came from —
  // see appliedBoosts() in app.js for why the indices could not survive the
  // trip. Everything below still reports normal-vision ratios; a boost chosen
  // under a simulation is a colour the design now holds, and this is what that
  // colour measures for everyone else.
  const boosts = palette.boosts || new Map();
  const lines = [`${header(palette, source)} — accessibility`, ''];

  lines.push('Against white and black');
  const nameWidth = Math.max(...colors.map((c) => c.name.length), 4);
  for (const row of againstExtremes(colors)) {
    lines.push(
      `  ${row.color.hex}  ${row.color.name.padEnd(nameWidth)}  ` +
      `on white ${ratioText(row.onWhite).padStart(7)} ${grade(row.onWhite).padEnd(9)}` +
      `on black ${ratioText(row.onBlack).padStart(7)} ${grade(row.onBlack)}`,
    );
  }

  lines.push('', 'Between palette colours');
  const label = (i) => String(i + 1).padStart(2);
  lines.push(`  ${' '.repeat(9 + nameWidth)}${colors.map((_, i) => label(i).padStart(6)).join('')}`);
  pairMatrix(colors).forEach((row, i) => {
    const cells = row.against.map((r) => (r === null ? '     —' : truncate(r, 1).toFixed(1).padStart(6))).join('');
    lines.push(`  ${label(i)} ${row.color.hex} ${row.color.name.padEnd(nameWidth)}${cells}`);
  });

  lines.push('', 'Likely pairings');
  const cards = buildCards(analysed);
  for (const card of cards) {
    const applied = boosts.get(card.id);
    const resolved = resolveCard(withBoosts(card, applied), null);
    const slots = Object.entries(resolved.slots)
      .map(([name, s]) => `${name} ${s.hex}`)
      .join(', ');
    lines.push(`  ${resolved.title} — ${slots}`);
    for (const boost of applied ? applied.values() : []) {
      lines.push(
        `      boosted: ${boost.slotLabel} ${boost.from} -> ${boost.to} ` +
        `(dE ${Math.round(boost.delta)}${boost.hueKept ? '' : ', chroma eased'}` +
        `${boost.under ? `, chosen under ${boost.under}` : ''}) — ` +
        'not one of the extracted colours',
      );
    }
    for (const check of resolved.checks) {
      const verdict = check.advisory
        ? `advisory — ${check.advisory}`
        : `needs ${check.need.toFixed(1)}  ${check.pass ? 'pass' : 'FAILS'}${check.grade ? `  ${check.grade}` : ''}`;
      lines.push(`    ${check.label.padEnd(22)}${ratioText(check.ratio).padStart(8)}  ${verdict}`);
      // A failure the reader can do something about is worth carrying into the
      // ticket with the remedy attached.
      const { boost } = check;
      if (!boost) continue;
      lines.push(
        `      boost:   ${boost.slotLabel} ${boost.from} -> ${boost.to} ` +
        `(dE ${Math.round(boost.delta)}${boost.hueKept ? '' : ', chroma eased'}) ` +
        `would clear ${check.need.toFixed(1)}`,
      );
    }
  }

  lines.push('', 'Alternatives from the rest of the palette');
  const alts = alternatives(cards, analysed, null);
  if (!alts.length) {
    lines.push('  Every colour is placed in a pairing above.');
  }
  for (const { color, placements } of alts) {
    lines.push(`  ${color.hex}  ${color.name}`);
    if (!placements.length) {
      lines.push('    nothing in the pairings above it can carry');
      continue;
    }
    for (const place of placements) {
      const where = `${place.cardTitle} / ${place.slotLabel}`;
      const weakest = place.checks.reduce((lo, c) => Math.min(lo, c.ratio), Infinity);
      lines.push(
        `    ${where.padEnd(34)}${ratioText(weakest).padStart(8)}  ` +
        `${place.fixes ? `fixes ${place.fixed.join(', ')}` : 'also works'}`,
      );
    }
  }

  lines.push('', 'Colour vision');
  let found = false;
  for (const [type, typeLabel] of Object.entries(CVD_TYPES)) {
    for (const pair of confusions(analysed, type)) {
      found = true;
      lines.push(
        `  ${typeLabel}: ${pair.a.name} and ${pair.b.name} become hard to tell apart ` +
        `(dE ${Math.round(pair.before)} -> ${Math.round(pair.after)}, contrast ${ratioText(pair.contrast)})`,
      );
    }
  }
  if (!found) {
    lines.push('  No pair in this palette collapses under protanopia, deuteranopia or tritanopia.');
  }
  lines.push('', 'Ratios are WCAG 2.2 relative luminance. Simulation is Machado et al. (2009).');

  return lines.join('\n') + '\n';
}

export function toJson(palette, source) {
  return JSON.stringify({
    name: palette.name,
    generator: 'palette.lab980.com',
    extractedAt: new Date().toISOString(),
    source: source
      ? { name: source.name, width: source.width, height: source.height, type: source.type }
      : null,
    sampledPixels: palette.sampled,
    extractionMs: palette.ms,
    colors: palette.colors.map((c) => ({
      name: c.name,
      slug: c.slug,
      role: c.role,
      hex: c.hex,
      rgb: { r: c.rgb.r, g: c.rgb.g, b: c.rgb.b },
      hsl: {
        h: Math.round(c.hsl.h),
        s: Math.round(c.hsl.s),
        l: Math.round(c.hsl.l),
      },
      share: Number(c.ratio.toFixed(4)),
    })),
  }, null, 2) + '\n';
}

export const FORMATS = {
  hex: { label: 'Hex list', ext: 'txt', mime: 'text/plain', build: (p) => toHexList(p) },
  text: { label: 'Text', ext: 'txt', mime: 'text/plain', build: toPlainText },
  css: { label: 'CSS variables', ext: 'css', mime: 'text/css', build: toCss },
  'tailwind-v3': { label: 'Tailwind v3 config', ext: 'js', mime: 'text/javascript', build: (p) => toTailwindV3(p) },
  'tailwind-v4': { label: 'Tailwind v4 @theme', ext: 'css', mime: 'text/css', build: (p) => toTailwindV4(p) },
  a11y: { label: 'Accessibility', ext: 'txt', mime: 'text/plain', build: toAccessibility },
  json: { label: 'JSON', ext: 'json', mime: 'application/json', build: toJson },
};

export function filenameFor(palette, ext) {
  const base = palette.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `${base || 'palette'}.${ext}`;
}
